### ISSUE TITLE
Out of date dependencies?

### ISSUE THREAD

**Issue by goanpeca** [glichtner/napari-pystackreg#7]
Hi @glichtner, looking into the project it seems `magicgui` is listed as a dependency but not used anymore?

Also `scikit-image` seems to be used  https://github.com/search?q=repo%3Aglichtner%2Fnapari-pystackreg%20skimage&type=code but is not being declared as a dependency.

Cheers!

**Comment by glichtner** [comment]
Hi @goanpeca,

Thanks for reporting. I've removed the magicgui dependency and added scikit-image for testing dependencies (however, both packages are installed by napari anyway).

Thanks,
Gregor

**Comment by goanpeca** [comment]
Hi @glichtner thanks for the fixes.

As a best practice suggestion, even if napari (or any other dependency) installs them, any explicitly declared dependency (as in imported and used by this package) should be listed explicitly as a dependency of this package.

Cheers!

**Comment by glichtner** [comment]
Hey,

of course I agree and I'm thankful that you made me aware that I had incorrectly specified the dependencies. Just wanted to mention it as in "as of the current version of napari, these dependencies are installed and therefore although I have updated the dependencies in the git repo, I haven't released a new version for napari-pystackreg just because of the incorrectly specified dependencies" :) 

Thanks again,
Gregor

**Comment by goanpeca** [comment]
Hello!

Happy to help! And no rush on a new release, I with other are helping  in the creation and maintenance of conda packages (and the recipes) for napari plugins so I try to keep and eye on any issues that appear.

Thanks again for the swift response!

Cheers 🚀
